spring:
  application:
    name: shipment-service

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/shipment_db}
    username: ${SPRING_DATASOURCE_USERNAME:logistics}
    password: ${SPRING_DATASOURCE_PASSWORD:logistics_password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  flyway:
    enabled: true

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health,info

  endpoint:
    health:
      show-details: always