spring:
  application:
    name: tracking-service

  datasource:
    url: jdbc:postgresql://localhost:5432/tracking_db
    username: logistics
    password: logistics_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  flyway:
    enabled: true

server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: health,info