services:

  postgres:
    image: postgres:17
    container_name: logistics-postgres

    environment:
      POSTGRES_DB: shipment_db
      POSTGRES_USER: logistics
      POSTGRES_PASSWORD: logistics_password

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U logistics -d shipment_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: