spring:
  application:
    name: location-ingestion-service

  kafka:
    bootstrap-servers: "${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka:9092}"

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

server:
  port: 8083

management:
  endpoints:
    web:
      exposure:
        include: health,info